version: '1'

services:
  parser-demo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: parser-demo
    ports:
      - "8050:8050" 
    restart: always
    environment:
      - CONTAINERNAME=parser-demo
      - OPENAI_API_KEY=${OPENAI_API_KEY}