version: '1'

services:
  parser-demo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: parser-demo
    network_mode: host  # Use host network mode
    restart: always
    environment:
      - CONTAINERNAME=parser-demo
